import time
def nextframe(timebetweenframes):
    time.sleep(timebetweenframes)
    for i in range(0):
        print("")

while True:
    nextframe(0.1)
    print("<0--------->")
    nextframe(0.1)
    print("<-0-------->")
    nextframe(0.1)
    print("<--0------->")
    nextframe(0.1)
    print("<---0------>")
    nextframe(0.1)
    print("<----0----->")
    nextframe(0.1)
    print("<-----0---->")
    nextframe(0.1)
    print("<------0--->")
    nextframe(0.1)
    print("<-------0-->")
    nextframe(0.1)
    print("<--------0->")
    nextframe(0.1)
    print("<---------0>")
    nextframe(0.1)
    print("<--------0->")
    nextframe(0.1)
    print("<-------0-->")
    nextframe(0.1)
    print("<------0--->")
    nextframe(0.1)
    print("<-----0---->")
    nextframe(0.1)
    print("<----0----->")
    nextframe(0.1)
    print("<---0------>")
    nextframe(0.1)
    print("<--0------->")
    nextframe(0.1)
    print("<-0-------->")